config/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version="v1",
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from users.apps import UsersConfig
from users.views import ActivationAPIView, APICodeGetAPIView, CodeGetAPIView, UserProfile, UserRetrieveAPIView

app_name = UsersConfig.name

urlpatterns = [
    path("api/get_code/", APICodeGetAPIView.as_view(), name="api_sms_code"),
    path("get_code/", CodeGetAPIView.as_view(), name="sms_code"),
    path("api/token/", TokenObtainPairView.as_view(permission_classes=[AllowAny]), name="token"),
    path("api/token/refresh/", TokenRefreshView.as_view(permission_classes=[AllowAny]), name="token_refresh"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("api/profile/", UserRetrieveAPIView.as_view(), name="api_user_detail"),
    path("accounts/profile/", UserProfile.as_view(), name="profile"),
    path("activate/", ActivationAPIView.as_view(), name="code_activation"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    phone = models.CharField(max_length=35, unique=True, verbose_name="номер телефона")
    invite_code = models.CharField(max_length=6, verbose_name="инвайт код")
    activate_code = models.CharField(max_length=6, **NULLABLE, verbose_name="инвайт код пригласившего пользователя")
    invited_by = models.ForeignKey(
        "self", on_delete=models.RESTRICT, **NULLABLE, verbose_name="пригласивший пользователь"
    )

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = []

users/views.py
from django.shortcuts import redirect
from django.urls import reverse
from drf_yasg.utils import swagger_auto_schema
from rest_framework import generics, mixins, status, views
from rest_framework.authentication import SessionAuthentication
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.renderers import BrowsableAPIRenderer, JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework_simplejwt.authentication import JWTTokenUserAuthentication

from users.models import User
from users.serializers import UserCreateSerializer, UserSerializer
from users.services import generate_invited_code, generate_password, send_code


class APICodeGetAPIView(mixins.CreateModelMixin, mixins.UpdateModelMixin, GenericAPIView):
    permission_classes = [AllowAny]
    queryset = User.objects.all()
    serializer_class = UserCreateSerializer

    def get_object(self):
        phone = self.request.data.get("phone")
        return User.objects.get(phone=phone)

    def perform_create(self, serializer):
        user = serializer.save()
        password = generate_password()
        user.set_password(password)
        while True:
            invite_code = generate_invited_code()
            if User.objects.filter(invite_code=invite_code).exists():
                continue
            else:
                user.invite_code = invite_code
                break
        send_code(user.phone, password)
        user.save()

    def perform_update(self, serializer):
        user = serializer.save()
        password = generate_password()
        user.set_password(password)
        send_code(user.phone, password)
        user.save()

    def post(self, request, *args, **kwargs):
        if self.request.data.get("phone"):
            phone = self.request.data.get("phone")
            if User.objects.filter(phone=phone).exists():
                return self.update(request, *args, **kwargs)
        return self.create(request, *args, **kwargs)


class CodeGetAPIView(APICodeGetAPIView):
    renderer_classes = [BrowsableAPIRenderer, JSONRenderer]

    def post(self, request, *args, **kwargs):
        if self.request.data.get("phone"):
            phone = self.request.data.get("phone")
            if User.objects.filter(phone=phone).exists():
                self.update(request, *args, **kwargs)
            else:
                self.create(request, *args, **kwargs)
        return redirect(reverse("users:login"))


class UserRetrieveAPIView(generics.RetrieveAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()

    def get_object(self):
        user = self.request.user
        return User.objects.filter(pk=user.pk).first()


class ActivationAPIView(generics.UpdateAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    authentication_classes = [SessionAuthentication, JWTTokenUserAuthentication]

    def get_object(self):
        user = self.request.user
        return User.objects.filter(pk=user.pk).first()

    def perform_update(self, serializer):
        user = serializer.save()
        activate_code = self.request.data.get("activate_code")
        if activate_code:
            user.invited_by = User.objects.filter(invite_code=activate_code).first()
        user.save()


class UserProfile(views.APIView):
    renderer_classes = [TemplateHTMLRenderer]
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    template_name = "users/profile.html"

    @swagger_auto_schema(
        operation_description="GET /accounts/profile/", responses={status.HTTP_200_OK: UserSerializer()}
    )
    def get(self, request):
        user = User.objects.filter(pk=request.user.pk)[0]
        return Response({"user": user})

users/templates/profile.html
{% extends "rest_framework/base.html" %}
{% load static %}

{% block bootstrap_theme %}
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css">
{% endblock %}


{% block bootstrap_navbar_variant %}{% endblock %}

{% block content%}

<div class="row text-center row-cols-1 row-cols-md-8 g-4">
    <div class="col-md-8">
        <div class="card border-primary mb-3" style="max-width: 540px;">

            <div class="card-header">Пользователь {{user.phone}}</div>
            <div class="card-body text-primary">
                <ul>
                    <li> Ваш инвайт код: {{ user.invite_code }}</li>
                    {% if user.activate_code is None %}
                    <li> Код приклашения не активирован</li>
                    {% else %}
                    <li>Код приглашения: {{ user.activate_code }}</li>
                    {% endif %}
                    {% if user.invited_users %}
                    <li>Номера приглашенных пользователей: {{ user.invited_users }}</li>
                    {% endif %}
                </ul>
            </div>
            <div class="btn-group">
                <a class="btn btn-sm btn-primary"
                   href="{% url 'users:code_activation' %}">Активация кода</a>
            </div>
        </div>
    </div>

</div>

{% endblock %}

users/templates/users/login.html
{% extends "rest_framework/base.html" %}
{% load static %}

{% block bootstrap_theme %}
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css">
{% endblock %}


{% block bootstrap_navbar_variant %}{% endblock %}

{% block content%}

<form method="post" action="" class="form-floating">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <div class="card">
                <div class="card-header text-center p-3"></div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Войти</button>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

users/templates/users/profile.html
{% extends "rest_framework/base.html" %}
{% load static %}

{% block bootstrap_theme %}
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css">
{% endblock %}


{% block bootstrap_navbar_variant %}{% endblock %}

{% block content%}

<div class="row text-center row-cols-1 row-cols-md-8 g-4">
    <div class="col-md-8">
        <div class="card border-primary mb-3" style="max-width: 540px;">

            <div class="card-header">Пользователь {{user.phone}}</div>
            <div class="card-body text-primary">
                <ul>
                    <li> Ваш инвайт код: {{ user.invite_code }}</li>
                    {% if user.activate_code is None %}
                    <li> Код приглашения не активирован</li>
                    {% else %}
                    <li>Активированный код приглашения: {{ user.activate_code }}</li>
                    {% endif %}
                    {% if user.invited_users %}
                    <li>Номера приглашенных пользователей: {{ user.invited_users }}</li>
                    {% endif %}
                </ul>
            </div>
            <div class="btn-group">
                <a class="btn btn-sm btn-primary"
                   href="{% url 'users:code_activation' %}">Активация кода</a>
                <a class="btn btn-sm btn-secondary"
                   href="{% url 'users:logout' %}">Выход</a>
            </div>

        </div>
    </div>

</div>

{% endblock %}